<div dojoType="dijit.layout.AccordionPane" title="Micropub">
 <div>
  <h2>Registered identities</h2>
  <table width="100%">
   <thead>
    <tr class="title">
     <td width="5%">Default</td>
     <td>Identity URL</td>
    </tr>
   </thead>
   <tbody>
    <?php foreach ($accounts as $accurl => $account) { ?>
     <tr>
      <td align='center'>
       <input disabled='1' dojoType="dijit.form.CheckBox" type="checkbox"/>
      </td>
      <td>
       <a href="<?= htmlspecialchars($accurl) ?>"><?= htmlspecialchars($accurl) ?></a>
      </td>
     </tr>
    <?php } ?>
   </tbody>
  </table>
 </div>

 <div>
  <h2>Add new identity</h2>
  <form method="post" action="backend.php">
   <input type="hidden" name="op" value="pluginhandler"/>
   <input type="hidden" name="plugin" value="micropub"/>
   <input type="hidden" name="method" value="action"/>
   <input type="hidden" name="mode"   value="authorize"/>

   <input name="url" type="url" size="40" dojoType="dijit.form.TextBox" required="1"/>
   <button type="submit">Authorize</button>
  </form>
 </div>
</div>
